version: 0.2
phases:
  pre_build:
    commands:
      - dotnet tool install --global dotnet-sonarscanner --version 4.7.1
      - export PATH="$PATH:/root/.dotnet/tools"
      - echo Restore started on `date`
      - dotnet restore SampleCore.csproj
  build:
    commands:
      - echo Build started on `date`
      - SonarScanner.MSBuild.exe begin /k:"project-key" 
      - MSBuild.exe <path to solution.sln> /t:Rebuild
      - SonarScanner.MSBuild.exe end
      - dotnet publish -c release -o ./build_output SampleCore.csproj
artifacts:
  files:
    - CodeBuild-SampleCore/build_output/**/*
    - scripts/**/*
    - appspec.yml
