version: 0.2
phases:
  pre_build:
    commands:
      - wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-3.3.0.1492-linux.zip
      - unzip ./sonar-scanner-cli-3.3.0.1492-linux.zip
      - export PATH=$PATH:/sonar-scanner-3.3.0.1492-linux/bin/
      - echo Restore started on `date`
      - dotnet restore SampleCore.csproj
  build:
    commands:
      - echo Build started on `date`
      - SonarScanner.MSBuild.exe begin /k:"project-key" 
      - MSBuild.exe <path to solution.sln> /t:Rebuild
      - SonarScanner.MSBuild.exe end
      - dotnet publish -c release -o ./build_output SampleCore.csproj
artifacts:
  files:
    - CodeBuild-SampleCore/build_output/**/*
    - scripts/**/*
    - appspec.yml
