version: 0.2
phases:
  pre_build:
    commands:
      - dotnet tool install --global dotnet-sonarscanner --version 4.7.1
      - export PATH="$PATH:/root/.dotnet/tools"
      - echo Restore started on `date`
      - dotnet restore SampleCore.csproj
  build:
    commands:
      - echo Build started on `date`
      - dotnet publish -c release -o ./build_output SampleCore.csproj
      - curl https://sonarcloud.io/api/qualitygates/project_status?projectKey=$Project >result.json
artifacts:
  files:
    - CodeBuild-SampleCore/build_output/**/*
    - scripts/**/*
    - appspec.yml
